---
# tasks file for opdk-update-component
#- block:
- name: Perform component update
  become: true
  become_user: root
  shell: '/opt/apigee/apigee-setup/bin/update.sh -c {{ component }} -f {{ target_response_file_path }}'
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
