---
# tasks file for opdk-update-component
#- block:
- name: Perform component update
  become: true
  become_user: root
  shell: '{{ apigee_update }} -c {{ component }} -f {{ opdk_installation_config_file }}'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
