---
# tasks file for opdk-update-component
#- block:
- name: Perform component update
  become: true
  shell: '{{ apigee_update }} -c {{ component }} -f {{ opdk_installation_config_file }}'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'

- name: Validate component starts
  become: true
  shell: '{{ apigee_all }} start'
  when: opdk_version | version_compare('4.16.01', '>=')
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'

- name: Wait for ready
  become: true
  shell: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'

- name: Component status
  become: true
  shell: '{{ apigee_all }} status'
  when: validate_ready | default(true) and opdk_version | version_compare('4.16.01', '>=')
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
