---
# tasks file for opdk-update-component
- name: Update apigee-setup
  shell: '{{ apigee_service }} apigee-setup update'

- name: Perform component update - {{ apigee_component }}
  shell: '{{ apigee_update }} -c {{ apigee_component }} -f {{ opdk_installation_config_file }}'
