---
# tasks file for opdk-update-component
- block:

  - name: Update apigee-setup
    shell: '{{ apigee_service }} apigee-setup update'

  - name: Perform component update - {{ apigee_component }}
    shell: '{{ apigee_update }} -c {{ apigee_component }} -f {{ opdk_installation_config_file }}'

  - name: Validate component status
    shell: '{{ apigee_all }} status'
    when: opdk_version | version_compare('4.16.01', '>=')

  rescue:

    - name: Validate status failed, trying component start...
      shell: '{{ apigee_all }} start'
      when: opdk_version | version_compare('4.16.01', '>=')

    - name: Small time delay for component boot, change with -e component_start_delay=
      pause:
        seconds: '{{ component_start_delay | default(1) }}'

- name: Validating component status a second time
  shell: '{{ apigee_all }} status'
  when: opdk_version | version_compare('4.16.01', '>=')