---
# tasks file for opdk-update-component
- block:

  - name: Update apigee-setup
    shell: '{{ apigee_service }} apigee-setup update'

  - name: Perform component update - {{ apigee_component }}
    shell: '{{ apigee_update }} -c {{ apigee_component }} -f {{ opdk_installation_config_file }}'

  - name: Wait for ready
    shell: '{{ apigee_all }} wait_for_ready'

  rescue:

    - name: Validate status failed, trying component start...
      shell: '{{ apigee_all }} start'
      when: opdk_version | version_compare('4.16.01', '>=')

- name: Wait for ready
  shell: '{{ apigee_all }} wait_for_ready'

- name: Validating component status
  shell: '{{ apigee_all }} status'
  when: opdk_version | version_compare('4.16.01', '>=')